### ISSUE TITLE
MessageSender (MS)

### ISSUE THREAD

**Issue by ilyar** [everscale-org/bounties#14]
# MessageSender (MS) [^1]
![image](https://user-images.githubusercontent.com/761285/163688562-d0a007f8-3525-4be4-ae52-52a70f350ec4.png)

## Intro

We call this system "Trinity Contracts". It is a simple testbed to test the blockchain
performance
TrinityRoot contract is supposed to deploy the MSDeployer when asked to do so. It also
funds it with some initial amount of gas.
Each MSDeployer immediately deploys The Trinity - 3 MS contracts in **different shards**
(lets discuss how to ensure that later, but I hope you'll find out how to do calc the shard
prefix from the contract address in tblkch.pdf [^2])

The initial mode for each MS is 0. MSDeployer can be asked to change it to 1 or 2.

## Mechanics

MSDeployer can be asked to send empty message to MS1 and initiate the load. What
happens after sending a message to MS?
In mode 0: nothing happens when message is received

In mode 1: messages will go from MS1 to MS2 then from MS2 to MS3 and back to MS1
then 2 then 3, etc. This is will be a simplest Timer implementation. But if you ping a Timer
once again, it will do the two 1-2-3-1-2-3 things in parallel. Thats how you can increase the
load linearly.

In mode 2: MS1 will send a message to 2 and 3. then each of them will send 2 messages to
neighbors. and neighbors will do the same again and again. The load will rise and rise
exponentially until some moment will be reached when balance of contracts is exhausted.

Then, you will add some stats collection to this system, so that some contract (for example
TrinityRoot) will know how much messages are sent per second and stop the exponential
mode to Timer mode at some point.

## User Story

We expect to see "Hey Trinity, here are some tokens and show me the highest load
possible" as an MVP.
On the second stage of development, we expect to see "Hey Trinity, lets exponentially grow

to 5000 TPS and keep it for an hour then stop. How much it will cost? Ok I have this
amount, lets go"

[^1]: [tps-generator.pdf](https://github.com/EverscaleGuild/bounties/files/8500515/tps-generator.pdf)
[^2]: [tblkch.pdf](https://github.com/EverscaleGuild/bounties/files/8500514/tblkch.pdf) [tblkch-ru.pdf](https://github.com/EverscaleGuild/bounties/files/8500519/tblkch-ru.pdf) [tvm.pdf](https://github.com/EverscaleGuild/bounties/files/8500516/tvm.pdf)  [tvm-ru.pdf](https://github.com/EverscaleGuild/bounties/files/8500517/tvm-ru.pdf)

**Comment by ilyar** [comment]
@pizza-777 https://t.me/EverscaleIncubator/563

**Comment by mnill** [comment]
Initially, this bounty was offered in everguild chat and we just forgot to create an issue for it. By now we already have a solution was made by @pizza-777
https://github.com/pizza-777/MessageSender

But @pizza-777 was stuck a bit and not solved it completely and this was solved with my help.

What we have now - fully-functional TPS generator for mode1 with a good readme.

By discussing with @eternalflow who is the bounty owner we decided to close this bounty as resolved and do not make mode2 and onchain history just because this result are good enough and we anyway need to wait for a gas price reduction which one was mentioned in everscale roadmap to go further.

As this bounty is much easier than others (especially after reduce on mode2 and history) and was solved by @pizza-777 with my help we also come to agreement with @pizza-777 and @isheldon to reduce bounty size to 4000 evers which was already paid to @pizza-777

So I suggest to close this issue as successfully resolved. 

@eternalflow Please confirm you are satisfied with result.
@pizza-777 Please confirm you are satisfied with the bounty size and received it.

**Comment by pizza-777** [comment]
Thank You for helping me! We made a fully working result. But I still wanna improving it in the visualization of transaction speed.  But it`s outside the scope of this bounty topic.

**Comment by ilyar** [comment]
https://github.com/EverscaleGuild/bounty-14-MessageSender/tree/01c2eb52e967618a66de9dfd719847d10e2b357f

**Comment by eternalflow** [comment]
@ilyar @mnill @pizza-777 

Hi! I confirm that the work has been done and payment was sent
