### ISSUE TITLE
Flatqube-NPM-Package

### ISSUE THREAD

**Issue by pizza-777** [everscale-org/bounties#37]
### Brief Introduction

[FlatQube ](https://flatqube.io/)is a decentralized exchange (DEX) for cryptocurrencies that provides convenient and secure trading of digital assets in a decentralized manner. In addition to trading, FlatQube also offers farming opportunities, allowing users to stake their tokens and earn rewards. FlatQube aims to simplify the process of swapping cryptocurrencies, managing liquidity pools, and participating in farming activities through its user-friendly platform.

### Goals

The goal of this proposal is to create an npm package that enables developers to interact with the FlatQube DEX in a seamless and automated manner. The npm package will provide functionalities such as automating swap transactions, retrieving cryptocurrency prices, managing liquidity by adding or removing tokens from pools, withdraw earning rewards from farming activities. The code of the package have to be covered by tests. 

### What's the result

The npm package will be developed using modern JavaScript/TypeScript language and will provide a comprehensive set of functions and utilities for interacting with the Flatqube DEX. The result of this work will be a fully functional npm package that can be integrated into any JavaScript/TypeScript project for seamless interaction with the Flatqube DEX. The package must be based on [native requests to the Everscale blockchain](https://github.com/tonlabs/ever-sdk-js), particularly [FlatQube contracts](https://github.com/broxus/flatqube-contracts)(not to [FlatQube API](https://docs.flatqube.io/integrate/open-api)). 

The community will receive a well-documented npm package that includes usage examples, code samples, and comprehensive documentation that outlines how to interact with the Flatqube DEX using the npm package. 

The code and documentation must be hosted on a public GitHub repository.

### Reward

The reward for completing this task will be divided into two milestones:

Milestone 1: Development of the Flatqube-NPM-Package - $1000 USDT.
This milestone involves the development of the npm package, including all the required functionalities mentioned in the issue. 

Milestone 2: Documentation - $500 USDT
This milestone involves the creation of comprehensive documentation, including usage examples, code samples for the npm package. 

Upon completion of both milestones, the total reward of $1500 USDT will be awarded  in EVERs or TIP3 tokens to the developer or team responsible for the successful completion of the project.

**Comment by danarrans** [comment]
Ready to take your order!

About me:
Arrans Ermakova Daniel, 19 years old

Telegram: @ISPDanWEB
Instagram: @ispanecweb
Behance: ISPDan

PER DAY FROM 5-12 HOURS OF WORK ON THE PROJECT

EXPERIENCE:
1. 3 years in figma
2. Programmers with 4+ years of experience work with me

COMPANY DATA WORKING WITH ME FROM JANUARY 2023

1. Company: "LLC House of the Architect", Kemerovo
Position: 2D; 3D designer in ArchiCAD

2. Company: "Bavaria Trade", Moscow
Position: UX/UI TILDA

3. Company: "Garand Plus", Moscow
Position: Beginner SEO

4. Company: "OknaVEKA", Tver
Position: Designer/SEO specialist

PROFESSIONAL SKILLS:
About me
1. FIGMA – 5/5 PORTFOLIO IN FIGMA (ALL IN FOLDERS) www.figma.com/file/ZNTdlU...
2. TILDA - 5/5
3. SEO - 3/5
4. ARCHICAD - 4/5 ON BEHANCE www.behance.net/ISPDan + Several works
5. ADOBE PHOTOSHOP - 4/5
6. ADOBE ILLUSTRETOR - 4/5

Ready to discuss everything in telegram or on the website

**Comment by pizza-777** [comment]
@danarrans  thanks for response. Please wait for @cryshado approving.

**Comment by Dhruv245** [comment]
Hi, Want to apply for this bounty.

**Comment by danarrans** [comment]
**Good night!**

My name is Daniel, I am the creator of the **ISPLIX** team

I, in the person of my team, would like to propose my candidacy!

Let me tell you a little about myself and the team:

I do design; website promotion for SEO.
Since January of this year, I have been cooperating with:

1. Company: "LLC House of the Architect", Kemerovo. Position: 2D; 3D designer in ArchiCAD
2. Company: "Bavaria Trade", Moscow. Position: UX/UI TILDA
3. Company: "Garand Plus", Moscow. Position: Beginner SEO
4. Company: "OknaVEKA", Tver. Position: Designer/SEO specialist

About the team:
My team includes:
1. Yuri - Head of GarandPlus. Position SEO website promotion. Freelancing experience 15 years. Average score from all sites 4.9/5.0
2. Cyril - Programmer. Worked at Yandex in Moscow. Average score 4.8/5.0
3. Igor - Programmer. Worked at Accenture in Tver. Average score 4.6/5.0
4. Cyril - Programmer. Worked at Yandex in Moscow. Average score 5.0/5.0
5. Artem - 3D designer in Poland. Average score 4.8/5.0
6. Angelica - SMM GarandPlus

We complete the work within the agreed time!

For the convenience of contacting you, I leave my data:

Telegram: **@ISPDanWEB**
Instagram: **@ispanecweb**

(For design customers)

PROFESSIONAL SKILLS:
About me
1. FIGMA – 5/5 PORTFOLIO IN FIGMA (ALL IN FOLDERS) www.figma.com/file/ZNTdlU...
2. TILDA - 5/5
3. SEO - 4/5
4. ARCHICAD - 4/5 ON BEHANCE www.behance.net/ISPDan + Several works
5. ADOBE PHOTOSHOP - 4/5
6. ADOBE ILLUSTRETOR - 4/5

**Comment by naftalimurgor** [comment]
Hey @cryshado 
I am ready to take on this having worked on  a similar project in the past, the GhostMarket TypeScript SDK here: https://github.com/OnBlockIO/ghostmarket-sdk-js

Deliverables would be:
- Functional Package with unit tests
- Example usage to help users quickly get started

Here are some of the previous NPM modules that I have worked on:

- https://www.npmjs.com/package/email-regexp
- https://www.npmjs.com/package/hrabi
- https://www.npmjs.com/package/web3-nodejs-provider
- https://www.npmjs.com/package/web3-covalent-sdk

Best regards,
Naftali

**Comment by qwadratic** [comment]
not sure we are ready to fund this from Broxus side, as we don't see much utility in it.
